### ISSUE TITLE
Responsive table CSS style missing

### ISSUE THREAD

**Issue by jakub-astrahit** [bootstrap-styled/v4#168]
# v4

## Issue Type

- [x] Bug (https://github.com/bootstrap-styled/v4/blob/master/.github/CONTRIBUTING.md#bug-reports)
- [ ] Feature (https://github.com/bootstrap-styled/v4/blob/master/.github/CONTRIBUTING.md#feature-requests)

## Description

When I use `<Table responsive={true}>...</Table>` it wraps the table with a div with a class `table-responsive` (that's OK) but it does not apply the styles because the styles for this class are missing. There should be a style for this class, something like:

```
.table-responsive { overflow: auto; }
```

## Steps to reproduce

Just use `<Table responsive={true}>...</Table>` and see the source code.

# Versions

- Node/NPM: 6.1.2
- OS: MacOS
- v4: 3.2.0

**Comment by kopax** [comment]
Hi and thanks.

Looking at https://github.com/bootstrap-styled/v4/blob/master/src/Table/index.js#L305 

It seems that this could be replaced :  

```diff
class TableUnstyled extends React.Component { // eslint-disable-line react/prefer-stateless-function
  static propTypes = propTypes;

  static defaultProps = defaultProps;

  render() {
    const {
      className,
      cssModule,
      size,
      bordered,
      striped,
      inverse,
      hover,
      reflow,
      responsive,
      tag: Tag,
-      responsiveTag: ResponsiveTag,
      ...attributes
    } = omit(this.props, ['theme']);

    const classes = mapToCssModules(cn(
      className,
      'table',
      size ? 'table-' + size : false, // eslint-disable-line
      responsive ? 'table-responsive' : false,
      bordered ? 'table-bordered' : false,
      striped ? 'table-striped' : false,
      inverse ? 'table-inverse' : false,
      hover ? 'table-hover' : false,
      reflow ? 'table-reflow' : false
    ), cssModule);

-    const table = <Tag {...attributes} className={classes} />;

-    if (responsive) {
-      return (
-        <ResponsiveTag className="table-responsive">{table}</ResponsiveTag>
-      );
-    }
-    return table;
+   return <Tag {...attributes} className={classes} />;
  }
}
```

this will remove the wrapper, I have no clue why but the css  says: 

```css
    /* Responsive tables
     Wrap your tables in '.table-responsive' and we'll make them mobile friendly
     by enabling horizontal scrolling. Only applies <768px. Everything above that
     will display normally.
     */
    
    &.table-responsive {
      display: block;
      width: 100%;
      overflow-x: auto;
      -ms-overflow-style: -ms-autohiding-scrollbar; /* See https://github.com/twbs/bootstrap/pull/10057 */
      &.table-bordered {
        border: 0;
      }
    }
 ```

I believe the comment is telling us that this should be a media query, according to https://github.com/twbs/bootstrap/blob/v4.3.1/scss/_tables.scss#L161

```css

// Responsive tables
//
// Generate series of `.table-responsive-*` classes for configuring the screen
// size of where your table will overflow.

.table-responsive {
  @each $breakpoint in map-keys($grid-breakpoints) {
    $next: breakpoint-next($breakpoint, $grid-breakpoints);
    $infix: breakpoint-infix($next, $grid-breakpoints);

    &#{$infix} {
      @include media-breakpoint-down($breakpoint) {
        display: block;
        width: 100%;
        overflow-x: auto;
        -webkit-overflow-scrolling: touch;

        // Prevent double border on horizontal scroll due to use of `display: block;`
        > .table-bordered {
          border: 0;
        }
      }
    }
  }
}
```


No clue about what the wrapper is in twbs/bootstrap, perhaps we should just update the css part and remove the wrapper.

Wanna fix this @jakub-astrahit  ?

**Comment by jakub-astrahit** [comment]
I don't think we should remove the wrapper. According to Bootstrap 4, a responsive table *should* be wrapped by a div. The question is, why is the css not working - i.e. why is `.table-responsive` being ignored?

**Comment by kopax** [comment]
I see two problem here : 

1. Outdated css (we built it on v4 alpha.3), we need to refresh our code to use the media queries.
2. Css for `.table-responsive` not being applied on wrapper component

For (2), this is because `styled-components` needs the component to receive `className` to append the vendor class to the component. We passe the vendor path to the `table`. 


Let's say the vendor is `.Adf46W`, then the `.table-responsive` class will work if `.Adf46W.table-responsive` is found, which is not the case in our current code.

I don't think there's a way to target a parent component from styled, the current structure is not excellent, we need to create two components and use the proper and updated `.table-responsive` for it.

**Comment by kopax** [comment]
To fix (1), I had a quick look to the css and started to write this : 

```js
    
    &.table-responsive {
      ${Object.keys(theme['$grid-breakpoints']).map((bp) => {
        const next =  breakpointNext(bp, theme['$grid-breakpoints']);
        const infix = breakpointInfix(next, theme['$grid-breakpoints']);
        return `
          &${infix} {
            ${mediaBreakpointDown(bp, theme['$grid-breakpoints'], `
              display: block;
              width: 100%;
              overflow-x: auto;
              -webkit-overflow-scrolling: touch;
      
              // Prevent double border on horizontal scroll due to use of display block
              > .table-bordered {
                border: 0;
              }
            `)}
          }
        `;
      }).join('
')}
    }
```

I've tested on bootstrap 4 website and I am not sure how this should be translated.

I must understand what  is the  css output of : 

```scss

.table-responsive {
  @each $breakpoint in map-keys($grid-breakpoints) {
    $next: breakpoint-next($breakpoint, $grid-breakpoints);
    $infix: breakpoint-infix($next, $grid-breakpoints);

    &#{$infix} {
      @include media-breakpoint-down($breakpoint) {
        display: block;
        width: 100%;
        overflow-x: auto;
        -webkit-overflow-scrolling: touch;

        // Prevent double border on horizontal scroll due to use of `display: block;`
        > .table-bordered {
          border: 0;
        }
      }
    }
  }
}
```

Long-time I have not done sass, I have tried to compile it online but no success, what does `&#{$infix}` generate?
