### ISSUE TITLE
[Feature request] Add `textAlign` and `verticalAlign` to Table component

### ISSUE THREAD

**Issue by kopax** [bootstrap-styled/v4#72]
# Table/Tr/Td

Add `textAlign` and `verticalAlign` to Table component

## Issue Type

- [x] Feature (https://github.com/bootstrap-styled/v4/blob/master/.github/CONTRIBUTING.md#feature-requests)

## Description

Add `textAlign` and `verticalAlign` to Table component

## Steps to reproduce

So far, td does not contain any class, but `vertical-align="middle` or `verticalAlign="middle"` none of them work even if attributes are on the dom element.

Instead there is a class on `Table` that force `Td` to `vertical-align: top`:

```css
.eSKtbX.table th, .eSKtbX.table td {
    padding: .75rem;
    vertical-align: top;
    border-top: 1px solid #eceeef;
}
```
